// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaBfgYfQ8qzI796Lmx9SOIHgCUe14d4w0',
    appId: '1:1008603233328:android:74efbbf0310452323641f5',
    messagingSenderId: '1008603233328',
    projectId: 'tubes-uas-final-2022',
    databaseURL: 'https://tubes-uas-final-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-uas-final-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2afT4iWWD33rEsZyhuVTdB6AIw9i1ZQ',
    appId: '1:1008603233328:ios:986f9bf6f3e4d0de3641f5',
    messagingSenderId: '1008603233328',
    projectId: 'tubes-uas-final-2022',
    databaseURL: 'https://tubes-uas-final-2022-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tubes-uas-final-2022.appspot.com',
    iosClientId: '1008603233328-utlijo6dgodt5u4l68p631abkkmgum4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesUasFinal',
  );
}
